version: "3.8"

services:
  app:
    build: .
    container_name: serverless_nest_app
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - dynamodb
    volumes:
      - .:/app
    command: /usr/local/bin/serverless offline --host 0.0.0.0 --stage production
    networks:
      - app_network

  dynamodb:
    image: amazon/dynamodb-local
    container_name: dynamodb_local
    ports:
      - "8000:8000"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
