service: my-nestjs-app

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  architecture: arm64
  stage: production
  region: us-east-2
  memorySize: 256
  logRetentionInDays: 1
  timeout: 15

  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:PutItem
            - dynamodb:Scan
            - dynamodb:Query
            - dynamodb:GetItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - arn:aws:dynamodb:us-east-2:343218210324:table/Logs
            - arn:aws:dynamodb:us-east-2:343218210324:table/Logs/index/*

        - Effect: Allow
          Action:
            - sns:Publish
          Resource:
            - !Ref ErrorSNSTopic
            - !Ref WarningSNSTopic
            - !Ref InfoSNSTopic

resources:
  Resources:
    ErrorSNSTopic:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: error-logs-topic

    WarningSNSTopic:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: warning-logs-topic

    InfoSNSTopic:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: info-logs-topic

functions:
  api:
    handler: dist/lambda.handler
    events:
      - httpApi:
          path: /{proxy+}
          method: any

plugins:
  - serverless-jetpack
  - serverless-offline
