name: Deployment Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  avoid_redundancy:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Redundant Builds
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}

  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Debug Info
        run: |
          pwd
          ls -la

      - name: Build
        run: npm run build

      - uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist

  terraform:
    runs-on: ubuntu-latest
    needs: build
    defaults:
      run:
        working-directory: terraform 
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Download dist artifact
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist
      # ▲▲▲ FIN DEL PASO AÑADIDO ▲▲▲

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2
      
      # ▼▼▼ PASO MODIFICADO ▼▼▼
      # Se ejecuta desde la raíz para encontrar 'dist' y crear 'build'.
      - name: Zip Lambda
        run: |
          mkdir -p build
          zip -r build/nestjs-api.zip . -i dist/
        working-directory: . # <-- Anula el 'working-directory' por defecto para este paso

      # ▼▼▼ PASO MODIFICADO ▼▼▼
      # Se ejecuta desde la raíz para encontrar 'build/nestjs-api.zip'.
      - name: Inspect ZIP content
        run: unzip -l build/nestjs-api.zip
        working-directory: . # <-- Anula el 'working-directory' por defecto para este paso

      # Los pasos de Terraform seguirán usando el 'working-directory: terraform' por defecto.
      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        # Asegúrate que tu archivo .tf busca el zip en la ruta correcta: ../build/nestjs-api.zip
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
